Parameters:
  ConfigurationName:
    Type: String
    Description: The Name of the Slack Confitaiton Name
  IAMPolicyArn:
    Type: String
    Description: The Role ARN for AWS Chatbot
  SlackChannelID:
    Type: String
    Description: The Slack Channel ID for AWS Chatbot to post messages to
  SlackWorkspaceID:
    Type: String
    Description: The Slack Team ID or WorkSpace ID
  SNSTopicArns:
    Type: CommaDelimitedList
    Description: Array of the Topic SNS Arns where AWS Chatbot subscribe to
  LoggingLevel:
    Type: String
    Default: ERROR
    AllowedValues:
      - ERROR
      - INFO
      - NONE
    Description: Specifies the logging level for this configuration. This property affects the log entries pushed to Amazon CloudWatch Logs. Logging levels include ERROR, INFO, or NONE.
Resources:
  DLAPCodebuildSlackConfig:
    Type: 'AWS::Chatbot::SlackChannelConfiguration'
    Properties:
      ConfigurationName: !Ref ConfigurationName
      IamRoleArn: !Ref IAMPolicyArn
      LoggingLevel: !Ref LoggingLevel
      SlackChannelId: !Ref SlackChannelID
      SlackWorkspaceId: !Ref SlackWorkspaceID
      SnsTopicArns: !Ref SNSTopicArns

Outputs:
  ConfigratioNameARN:
    Description: AWS Chatbot ConfigraitonName ARN
    Value: !Ref DLAPCodebuildSlackConfig